# -*- coding: utf-8 -*-
"""TensorFlow1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KH5KFnn-3ZvJXBIooh3Xa3OukAKORLDV
"""

from tensorflow.keras.datasets import mnist
from tensorflow.python.client import device_lib

from tensorflow.keras.utils import to_categorical

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras import backend as K
from tensorflow.keras.optimizers import SGD

from tensorflow.keras.models import load_model

import cv2
import numpy as np
import matplotlib.pyplot as plt

import idx2numpy

def imshow(title, image = None, size = 6):
    w, h = image.shape[0], image.shape[1]
    aspect_ratio = w/h
    plt.figure(figsize=(size*aspect_ratio, size))
    plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    plt.title(title)
    plt.show()

def main():
    print("Hello, World!")
    
    train_img_path = 'dati/SAllenamento/train-images.idx3-ubyte'
    train_lbl_path = 'dati/SAllenamento/train-labels.idx1-ubyte'
    test_img_path = 'dati/STest/t10k-images.idx3-ubyte'
    test_lbl_path = 'dati/STest/t10k-labels.idx1-ubyte'

    # Carica i file locali
    x_train = idx2numpy.convert_from_file(train_img_path)
    y_train = idx2numpy.convert_from_file(train_lbl_path)
    x_test = idx2numpy.convert_from_file(test_img_path)
    y_test = idx2numpy.convert_from_file(test_lbl_path)

    #posizione del modello salvatoF
    model_path = "export/mnist_ai_1_0.h5"


    print(device_lib.list_local_devices())

    """# Inspecting our data"""

    print("Initial shape or dimensions of x_train : " + str(x_train.shape))


    for i in range(0,4):
        random_num = np.random.randint(0, len(x_train))
        img = x_train[random_num]
        imshow(f"sample{i}", img, size = 2)

    """# Preprocessing our dataset"""

    img_rows = x_train[0].shape[0]
    img_cols = x_train[0].shape[1]

    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)

    input_shape = (img_rows, img_cols, 1)

    x_train = x_train.astype('float32')
    x_test = x_test.astype('float32')

    x_train /= 255.0
    x_test /= 255.0

    print("x_train shape : ", x_train.shape)
    print("x_test shape : ", x_test.shape)

    """# One hot encode our labels"""

    y_train = to_categorical(y_train)
    y_test = to_categorical(y_test)

    print('y_train : ', y_train.shape)
    print('y_test : ', y_test.shape)

    num_classes = y_test.shape[1]

    y_train[0]

    """# Building the model"""


    model = Sequential()
    model.add(Conv2D(32, kernel_size = (3, 3), activation = 'relu', input_shape = input_shape))
    model.add(Conv2D(64, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Flatten())
    model.add(Dense(128, activation = 'relu'))
    model.add(Dense(num_classes, activation = 'softmax'))

    model.compile(loss = 'categorical_crossentropy',
                optimizer = SGD(0.001),
                metrics = ['accuracy'])
    print(model.summary())

    """# Training the model"""

    batch_size = 128
    epochs = 25

    history = model.fit(x_train,
                        y_train,
                        batch_size=batch_size,
                        epochs=epochs,
                        verbose=1,
                        validation_data = (x_test, y_test))

    score = model.evaluate(x_test, y_test, verbose=0)
    print('Test loss : ', score[0])
    print('Test accuracy : ', score[1])

    history_dict = history.history
    history_dict

    x_test.shape

    model.save(model_path)
    print("model saved")

    classifier = load_model(model_path)

    print("predicting classes for all 10000 test images")
    pred = np.argmax(classifier.predict(x_test), axis=-1)
    print("completed")

    print(pred)
    print(type(pred))
    print(len(pred))

    input_img = x_test[29]
    imshow('img', input_img)
    print(input_img.shape)

    input_img = input_img.reshape(1, 28, 28, 1)
    print(input_img.shape)

    pred = np.argmax(classifier.predict(input_img), axis=-1)
    print(pred)
    print(type(pred))
    print(len(pred))

if __name__ == "__main__":
    main()